server:
  port: 8889
spring:
  application:
    name: redbook-service-message
  rabbitmq:
    host: 123.206.101.247
    port: 5672
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:your_rabbitmq_password}
    virtual-host: /